name: A workflow for my Hello World file
on: push

jobs:
  build:
   name: Hello world action
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - name: show ref
       run: echo $GITHUB_REF
     - name: get tag
       id: get_tag
       run: |
         echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
         echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
         echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
     - name: show_version
       run: |
         echo $SOURCE_NAME 
         echo $SOURCE_BRANCH 
         echo $SOURCE_TAG
       env:
          SOURCE_NAME: ${{ steps.get_tag.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.get_tag.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.get_tag.outputs.SOURCE_TAG }}
     - uses: ./action-a
       with:
         MY_NAME: "Ben"
      
